//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Accounts')
export class AccountsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  accountId: string;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  accountNumber: string;

  @Column('text', { nullable: true })
  accountType: string;

  @Column('real', { nullable: true })
  balance: number;
}
