//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Currencies')
export class CurrenciesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  currencyId: string;

  @Column('text', { nullable: true })
  currencyName: string;

  @Column('text', { nullable: true })
  currencySymbol: string;

  @Column('real', { nullable: true })
  exchangeRate: number;

  @Column('integer', { nullable: true })
  walletId: number;
}
