//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const CurrenciesTitle = () => {
  const record = useRecordContext();
  return <span>Currencies {record ? `"${record.currencyId}"` : ''}</span>;
};

export const CurrenciesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="currencyId" />
      <TextField source="currencyName" />
      <TextField source="currencySymbol" />
      <NumberField source="exchangeRate" />
      <ReferenceField source="walletId" reference="users" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const CurrenciesEdit = () => (
  <Edit title={<CurrenciesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="currencyId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="currencyName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="currencySymbol" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="exchangeRate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="walletId" reference="users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const CurrenciesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="currencyId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="currencyName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="currencySymbol" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="exchangeRate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="walletId" reference="users" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="walletId"
    label="walletId"
    reference="users"
    alwaysOn
  />,
];
