//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const TransactionsTitle = () => {
  const record = useRecordContext();
  return <span>Transactions {record ? `"${record.transactionId}"` : ''}</span>;
};

export const TransactionsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="transactionId" />
      <ReferenceField source="senderId" reference="users" />
      <ReferenceField source="receiverId" reference="users" />
      <NumberField source="amount" />
      <ReferenceField source="currency" reference="currencies" />
      <DateField source="transactionDate" />
      <ReferenceField source="accountBalance" reference="accounts" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const TransactionsEdit = () => (
  <Edit title={<TransactionsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="transactionId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="senderId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="amount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="currency" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="transactionDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="accountBalance" reference="accounts" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const TransactionsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="transactionId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="senderId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiverId" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="amount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="currency" reference="currencies" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="transactionDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="accountBalance" reference="accounts" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="senderId"
    label="senderId"
    reference="users"
    alwaysOn
  />,
  <ReferenceInput
    source="receiverId"
    label="receiverId"
    reference="users"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="currency"
    label="currency"
    reference="currencies"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="accountBalance"
    label="accountBalance"
    reference="accounts"
    alwaysOn
  />,
];
