//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: {
        name: 'Name',
        email: 'Email',
        password: 'Password',
        phoneNumber: 'Phone Number',
        id: 'id',
      },
    },
    Transactions: {
      name: 'Transactions',
      fields: {
        transactionId: 'Transaction Id',
        senderId: 'Sender Id',
        receiverId: 'Receiver Id',
        amount: 'Amount',
        currency: 'Currency',
        transactionDate: 'Transaction Date',
        accountBalance: 'Account Balance',
        id: 'id',
      },
    },
    Accounts: {
      name: 'Accounts',
      fields: {
        accountId: 'Account Id',
        userId: 'User Id',
        accountNumber: 'Account Number',
        accountType: 'Account Type',
        balance: 'Balance',
        id: 'id',
      },
    },
    Currencies: {
      name: 'Currencies',
      fields: {
        currencyId: 'Currency Id',
        currencyName: 'Currency Name',
        currencySymbol: 'Currency Symbol',
        exchangeRate: 'Exchange Rate',
        walletId: 'Wallet Id',
        id: 'id',
      },
    },
    Admin: {
      name: 'Admin',
      fields: {
        adminId: 'Admin Id',
        name: 'Name',
        email: 'Email',
        password: 'Password',
        permissions: 'Permissions',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        phoneNumber: 'Phone Number (fr)',
        id: 'id',
      },
    },
    Transactions: {
      name: 'Transactions (fr)',
      fields: {
        transactionId: 'Transaction Id (fr)',
        senderId: 'Sender Id (fr)',
        receiverId: 'Receiver Id (fr)',
        amount: 'Amount (fr)',
        currency: 'Currency (fr)',
        transactionDate: 'Transaction Date (fr)',
        accountBalance: 'Account Balance (fr)',
        id: 'id',
      },
    },
    Accounts: {
      name: 'Accounts (fr)',
      fields: {
        accountId: 'Account Id (fr)',
        userId: 'User Id (fr)',
        accountNumber: 'Account Number (fr)',
        accountType: 'Account Type (fr)',
        balance: 'Balance (fr)',
        id: 'id',
      },
    },
    Currencies: {
      name: 'Currencies (fr)',
      fields: {
        currencyId: 'Currency Id (fr)',
        currencyName: 'Currency Name (fr)',
        currencySymbol: 'Currency Symbol (fr)',
        exchangeRate: 'Exchange Rate (fr)',
        walletId: 'Wallet Id (fr)',
        id: 'id',
      },
    },
    Admin: {
      name: 'Admin (fr)',
      fields: {
        adminId: 'Admin Id (fr)',
        name: 'Name (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        permissions: 'Permissions (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
